Modify deploy workflow to use self-hosted runner
Updated the workflow to run on a self-hosted runner and added steps to install Nginx if not present.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,9 +14,28 @@ on:
 # Jobs in workflow. 
 jobs:
   code-checkout:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     # Steps in workflow.
     steps:
+      - name: Clone Code
+        uses: actions/checkout@v7
+      - name: Deploy via Nginx
+        run: |
+          # Check if Nginx is installed
+          if ! command -v nginx &> /dev/null; then
+            echo "Nginx not found. Installing Nginx..."
+            sudo apt-get update -y
+            sudo apt-get install -y nginx
+            sudo systemctl enable nginx
+            sudo systemctl start nginx
+          else
+            echo "Nginx is already installed. Skipping installation."
+          fi
+
+          # Copy portfolio file to web root
+          sudo cp vaibhav-godse-portfolio.html /var/www/html/index.html
+          
+      
       - name: Deploy the code
         run: echo "Code Deployed to AWS EC2 instance"
